"""inbox offer fields

Revision ID: 0ab86cb62048
Revises: 5c3b3abc5b81
Create Date: 2026-04-30 11:29:41.489473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0ab86cb62048'
down_revision: Union[str, Sequence[str], None] = '5c3b3abc5b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inboxes', sa.Column('offer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inboxes', sa.Column('offer_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inboxes', 'offer_until')
    op.drop_column('inboxes', 'offer_text')
    # ### end Alembic commands ###
