"""deereach_v2_satang_messages_channel_prefs

Revision ID: 3c6192bdf262
Revises: 0005
Create Date: 2026-04-28 18:46:24.194773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3c6192bdf262'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_shop_mutes',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'shop_id')
    )
    op.create_table('deereach_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_satang', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['deereach_campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deereach_messages_campaign_id'), 'deereach_messages', ['campaign_id'], unique=False)
    op.drop_index(op.f('ix_branch_shop_id'), table_name='branches')
    op.create_index(op.f('ix_branches_shop_id'), 'branches', ['shop_id'], unique=False)
    op.add_column('customers', sa.Column('preferred_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_customer_line_id'), table_name='customers')
    op.drop_index(op.f('ix_customer_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_line_id'), 'customers', ['line_id'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    # Add new DeeReach campaign columns with server defaults so existing rows
    # (old "credits_spent" era sends) don't violate the NOT NULL constraint.
    # status='completed' because any pre-migration send was fully processed;
    # both credit fields default to 0 (legacy rows had no satang breakdown).
    op.add_column('deereach_campaigns', sa.Column(
        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False,
        server_default='completed',
    ))
    op.add_column('deereach_campaigns', sa.Column(
        'locked_credits_satang', sa.Integer(), nullable=False,
        server_default='0',
    ))
    op.add_column('deereach_campaigns', sa.Column(
        'final_credits_satang', sa.Integer(), nullable=False,
        server_default='0',
    ))
    op.drop_column('deereach_campaigns', 'credits_spent')
    op.drop_index(op.f('ix_offer_source_shop_id'), table_name='offers')
    op.drop_index(op.f('ix_offer_target_customer_id'), table_name='offers')
    op.drop_index(op.f('ix_offer_target_shop_id'), table_name='offers')
    op.create_index(op.f('ix_offers_source_shop_id'), 'offers', ['source_shop_id'], unique=False)
    op.create_index(op.f('ix_offers_target_customer_id'), 'offers', ['target_customer_id'], unique=False)
    op.create_index(op.f('ix_offers_target_shop_id'), 'offers', ['target_shop_id'], unique=False)
    op.drop_index(op.f('ix_point_branch_id'), table_name='points')
    op.drop_index(op.f('ix_point_customer_id'), table_name='points')
    op.drop_index(op.f('ix_point_redemption_id'), table_name='points')
    op.drop_index(op.f('ix_point_shop_id'), table_name='points')
    op.create_index(op.f('ix_points_branch_id'), 'points', ['branch_id'], unique=False)
    op.create_index(op.f('ix_points_customer_id'), 'points', ['customer_id'], unique=False)
    op.create_index(op.f('ix_points_redemption_id'), 'points', ['redemption_id'], unique=False)
    op.create_index(op.f('ix_points_shop_id'), 'points', ['shop_id'], unique=False)
    op.drop_index(op.f('ix_redemption_branch_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemption_customer_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemption_shop_id'), table_name='redemptions')
    op.create_index(op.f('ix_redemptions_branch_id'), 'redemptions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_redemptions_customer_id'), 'redemptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_redemptions_shop_id'), 'redemptions', ['shop_id'], unique=False)
    op.drop_index(op.f('ix_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referral_referee_shop_id'), table_name='referrals')
    op.drop_index(op.f('ix_referral_referrer_shop_id'), table_name='referrals')
    op.create_index(op.f('ix_referrals_code'), 'referrals', ['code'], unique=True)
    op.create_index(op.f('ix_referrals_referee_shop_id'), 'referrals', ['referee_shop_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_shop_id'), 'referrals', ['referrer_shop_id'], unique=False)
    op.drop_index(op.f('ix_shop_line_id'), table_name='shops')
    op.drop_index(op.f('ix_shop_owner_email'), table_name='shops')
    op.drop_index(op.f('ix_shop_phone'), table_name='shops')
    op.create_index(op.f('ix_shops_line_id'), 'shops', ['line_id'], unique=True)
    op.create_index(op.f('ix_shops_owner_email'), 'shops', ['owner_email'], unique=True)
    op.create_index(op.f('ix_shops_phone'), 'shops', ['phone'], unique=True)
    op.drop_column('shops', 'shop_pin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('shop_pin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shops_phone'), table_name='shops')
    op.drop_index(op.f('ix_shops_owner_email'), table_name='shops')
    op.drop_index(op.f('ix_shops_line_id'), table_name='shops')
    op.create_index(op.f('ix_shop_phone'), 'shops', ['phone'], unique=True)
    op.create_index(op.f('ix_shop_owner_email'), 'shops', ['owner_email'], unique=True)
    op.create_index(op.f('ix_shop_line_id'), 'shops', ['line_id'], unique=True)
    op.drop_index(op.f('ix_referrals_referrer_shop_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referee_shop_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_code'), table_name='referrals')
    op.create_index(op.f('ix_referral_referrer_shop_id'), 'referrals', ['referrer_shop_id'], unique=False)
    op.create_index(op.f('ix_referral_referee_shop_id'), 'referrals', ['referee_shop_id'], unique=False)
    op.create_index(op.f('ix_referral_code'), 'referrals', ['code'], unique=True)
    op.drop_index(op.f('ix_redemptions_shop_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_customer_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_branch_id'), table_name='redemptions')
    op.create_index(op.f('ix_redemption_shop_id'), 'redemptions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_redemption_customer_id'), 'redemptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_redemption_branch_id'), 'redemptions', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_points_shop_id'), table_name='points')
    op.drop_index(op.f('ix_points_redemption_id'), table_name='points')
    op.drop_index(op.f('ix_points_customer_id'), table_name='points')
    op.drop_index(op.f('ix_points_branch_id'), table_name='points')
    op.create_index(op.f('ix_point_shop_id'), 'points', ['shop_id'], unique=False)
    op.create_index(op.f('ix_point_redemption_id'), 'points', ['redemption_id'], unique=False)
    op.create_index(op.f('ix_point_customer_id'), 'points', ['customer_id'], unique=False)
    op.create_index(op.f('ix_point_branch_id'), 'points', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_offers_target_shop_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_target_customer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_source_shop_id'), table_name='offers')
    op.create_index(op.f('ix_offer_target_shop_id'), 'offers', ['target_shop_id'], unique=False)
    op.create_index(op.f('ix_offer_target_customer_id'), 'offers', ['target_customer_id'], unique=False)
    op.create_index(op.f('ix_offer_source_shop_id'), 'offers', ['source_shop_id'], unique=False)
    op.add_column('deereach_campaigns', sa.Column('credits_spent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('deereach_campaigns', 'final_credits_satang')
    op.drop_column('deereach_campaigns', 'locked_credits_satang')
    op.drop_column('deereach_campaigns', 'status')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_line_id'), table_name='customers')
    op.create_index(op.f('ix_customer_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customer_line_id'), 'customers', ['line_id'], unique=True)
    op.drop_column('customers', 'preferred_channel')
    op.drop_index(op.f('ix_branches_shop_id'), table_name='branches')
    op.create_index(op.f('ix_branch_shop_id'), 'branches', ['shop_id'], unique=False)
    op.drop_index(op.f('ix_deereach_messages_campaign_id'), table_name='deereach_messages')
    op.drop_table('deereach_messages')
    op.drop_table('customer_shop_mutes')
    # ### end Alembic commands ###
