"""offers and referrals

Revision ID: 4153748364bb
Revises: dc642ea6d5c9
Create Date: 2026-04-25 19:20:54.649090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4153748364bb'
down_revision: Union[str, Sequence[str], None] = 'dc642ea6d5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_shop_id', sa.Uuid(), nullable=True),
    sa.Column('source_customer_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_shop_id', sa.Uuid(), nullable=True),
    sa.Column('target_customer_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['source_shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['target_customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['target_shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_source_shop_id'), 'offer', ['source_shop_id'], unique=False)
    op.create_index(op.f('ix_offer_target_customer_id'), 'offer', ['target_customer_id'], unique=False)
    op.create_index(op.f('ix_offer_target_shop_id'), 'offer', ['target_shop_id'], unique=False)
    op.create_table('referral',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referrer_shop_id', sa.Uuid(), nullable=False),
    sa.Column('referee_shop_id', sa.Uuid(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referee_shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['referrer_shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_code'), 'referral', ['code'], unique=True)
    op.create_index(op.f('ix_referral_referee_shop_id'), 'referral', ['referee_shop_id'], unique=False)
    op.create_index(op.f('ix_referral_referrer_shop_id'), 'referral', ['referrer_shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_referrer_shop_id'), table_name='referral')
    op.drop_index(op.f('ix_referral_referee_shop_id'), table_name='referral')
    op.drop_index(op.f('ix_referral_code'), table_name='referral')
    op.drop_table('referral')
    op.drop_index(op.f('ix_offer_target_shop_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_target_customer_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_source_shop_id'), table_name='offer')
    op.drop_table('offer')
    # ### end Alembic commands ###
