"""shop story_text thanks_message

Revision ID: 44dbb7bac7dd
Revises: e81d6ae1909a
Create Date: 2026-04-29 13:37:03.411907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '44dbb7bac7dd'
down_revision: Union[str, Sequence[str], None] = 'e81d6ae1909a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('thanks_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shops', sa.Column('story_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'story_text')
    op.drop_column('shops', 'thanks_message')
    # ### end Alembic commands ###
