"""staff invite token

Revision ID: 4fea385d541e
Revises: 0ab86cb62048
Create Date: 2026-04-30 22:15:03.544442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4fea385d541e'
down_revision: Union[str, Sequence[str], None] = '0ab86cb62048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_members', sa.Column('invite_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staff_members', sa.Column('invite_token_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_staff_members_invite_token'), 'staff_members', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_members_invite_token'), table_name='staff_members')
    op.drop_column('staff_members', 'invite_token_expires_at')
    op.drop_column('staff_members', 'invite_token')
    # ### end Alembic commands ###
