"""customer text_size

Revision ID: 5c3b3abc5b81
Revises: aae7ef815356
Create Date: 2026-04-29 18:41:23.195011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5c3b3abc5b81'
down_revision: Union[str, Sequence[str], None] = 'aae7ef815356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('text_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'text_size')
    # ### end Alembic commands ###
