"""deereach inbox + customer web_push_endpoint

Revision ID: 76cf2a5cd889
Revises: 3c6192bdf262
Create Date: 2026-04-28 21:02:48.305286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '76cf2a5cd889'
down_revision: Union[str, Sequence[str], None] = '3c6192bdf262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inboxes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['deereach_campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inboxes_campaign_id'), 'inboxes', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_inboxes_created_at'), 'inboxes', ['created_at'], unique=False)
    op.create_index(op.f('ix_inboxes_customer_id'), 'inboxes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_inboxes_shop_id'), 'inboxes', ['shop_id'], unique=False)
    op.add_column('customers', sa.Column('web_push_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'web_push_endpoint')
    op.drop_index(op.f('ix_inboxes_shop_id'), table_name='inboxes')
    op.drop_index(op.f('ix_inboxes_customer_id'), table_name='inboxes')
    op.drop_index(op.f('ix_inboxes_created_at'), table_name='inboxes')
    op.drop_index(op.f('ix_inboxes_campaign_id'), table_name='inboxes')
    op.drop_table('inboxes')
    # ### end Alembic commands ###
