"""shop_items table for dashboard claimables

Revision ID: 8a75f4f1420e
Revises: 72979e312743
Create Date: 2026-04-29 08:04:34.357588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8a75f4f1420e'
down_revision: Union[str, Sequence[str], None] = '72979e312743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'kind', name='uq_shop_items_shop_kind')
    )
    op.create_index(op.f('ix_shop_items_shop_id'), 'shop_items', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_items_shop_id'), table_name='shop_items')
    op.drop_table('shop_items')
    # ### end Alembic commands ###
