"""web push subscription keys (p256dh + auth)

Revision ID: 8d9f121dbc94
Revises: 76cf2a5cd889
Create Date: 2026-04-28 21:16:57.934312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8d9f121dbc94'
down_revision: Union[str, Sequence[str], None] = '76cf2a5cd889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('web_push_p256dh', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('customers', sa.Column('web_push_auth', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'web_push_auth')
    op.drop_column('customers', 'web_push_p256dh')
    # ### end Alembic commands ###
