"""initial schema

Revision ID: 9931050e429e
Revises: 
Create Date: 2026-04-25 09:29:40.144190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9931050e429e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('line_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_line_id'), 'customer', ['line_id'], unique=True)
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.create_table('otpcode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otpcode_phone'), 'otpcode', ['phone'], unique=False)
    op.create_table('shop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('line_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('reward_threshold', sa.Integer(), nullable=False),
    sa.Column('reward_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuance_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reward_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shop_pin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('theme_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_line_id'), 'shop', ['line_id'], unique=True)
    op.create_index(op.f('ix_shop_owner_email'), 'shop', ['owner_email'], unique=True)
    op.create_index(op.f('ix_shop_phone'), 'shop', ['phone'], unique=True)
    op.create_table('branch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_shop_id'), 'branch', ['shop_id'], unique=False)
    op.create_table('creditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staffmember',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('line_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('can_void', sa.Boolean(), nullable=False),
    sa.Column('can_deereach', sa.Boolean(), nullable=False),
    sa.Column('can_topup', sa.Boolean(), nullable=False),
    sa.Column('can_settings', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staffmember_line_id'), 'staffmember', ['line_id'], unique=False)
    op.create_index(op.f('ix_staffmember_phone'), 'staffmember', ['phone'], unique=False)
    op.create_index(op.f('ix_staffmember_shop_id'), 'staffmember', ['shop_id'], unique=False)
    op.create_table('topupslip',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('slip_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slip_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_hash')
    )
    op.create_table('redemption',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by_staff_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['voided_by_staff_id'], ['staffmember.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemption_branch_id'), 'redemption', ['branch_id'], unique=False)
    op.create_index(op.f('ix_redemption_customer_id'), 'redemption', ['customer_id'], unique=False)
    op.create_index(op.f('ix_redemption_shop_id'), 'redemption', ['shop_id'], unique=False)
    op.create_table('stamp',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('issuance_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_by_staff_id', sa.Uuid(), nullable=True),
    sa.Column('redemption_id', sa.Uuid(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by_staff_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['issued_by_staff_id'], ['staffmember.id'], ),
    sa.ForeignKeyConstraint(['redemption_id'], ['redemption.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['voided_by_staff_id'], ['staffmember.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stamp_branch_id'), 'stamp', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stamp_customer_id'), 'stamp', ['customer_id'], unique=False)
    op.create_index(op.f('ix_stamp_redemption_id'), 'stamp', ['redemption_id'], unique=False)
    op.create_index(op.f('ix_stamp_shop_id'), 'stamp', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stamp_shop_id'), table_name='stamp')
    op.drop_index(op.f('ix_stamp_redemption_id'), table_name='stamp')
    op.drop_index(op.f('ix_stamp_customer_id'), table_name='stamp')
    op.drop_index(op.f('ix_stamp_branch_id'), table_name='stamp')
    op.drop_table('stamp')
    op.drop_index(op.f('ix_redemption_shop_id'), table_name='redemption')
    op.drop_index(op.f('ix_redemption_customer_id'), table_name='redemption')
    op.drop_index(op.f('ix_redemption_branch_id'), table_name='redemption')
    op.drop_table('redemption')
    op.drop_table('topupslip')
    op.drop_index(op.f('ix_staffmember_shop_id'), table_name='staffmember')
    op.drop_index(op.f('ix_staffmember_phone'), table_name='staffmember')
    op.drop_index(op.f('ix_staffmember_line_id'), table_name='staffmember')
    op.drop_table('staffmember')
    op.drop_table('creditlog')
    op.drop_index(op.f('ix_branch_shop_id'), table_name='branch')
    op.drop_table('branch')
    op.drop_index(op.f('ix_shop_phone'), table_name='shop')
    op.drop_index(op.f('ix_shop_owner_email'), table_name='shop')
    op.drop_index(op.f('ix_shop_line_id'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_otpcode_phone'), table_name='otpcode')
    op.drop_table('otpcode')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_index(op.f('ix_customer_line_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
