"""redemption served_at

Revision ID: aae7ef815356
Revises: 44dbb7bac7dd
Create Date: 2026-04-29 14:31:00.235327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae7ef815356'
down_revision: Union[str, Sequence[str], None] = '44dbb7bac7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemptions', sa.Column('served_at', sa.DateTime(), nullable=True))
    op.add_column('redemptions', sa.Column('served_by_staff_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'redemptions', 'staff_members', ['served_by_staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'redemptions', type_='foreignkey')
    op.drop_column('redemptions', 'served_by_staff_id')
    op.drop_column('redemptions', 'served_at')
    # ### end Alembic commands ###
