"""add grant_id to points

Revision ID: cc14b080239d
Revises: a1b2c3d4e5f7
Create Date: 2026-05-03 17:20:10.150793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc14b080239d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'is_pwa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('points', sa.Column('grant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_points_grant_id'), 'points', ['grant_id'], unique=False)
    op.create_index('ix_points_shop_customer_active', 'points', ['shop_id', 'customer_id', 'is_voided', 'redemption_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_points_shop_customer_active', table_name='points')
    op.drop_index(op.f('ix_points_grant_id'), table_name='points')
    op.drop_column('points', 'grant_id')
    op.alter_column('customers', 'is_pwa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
