"""shop is_onboarded

Revision ID: d0304fed97cc
Revises: 9931050e429e
Create Date: 2026-04-25 16:38:20.352479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0304fed97cc'
down_revision: Union[str, Sequence[str], None] = '9931050e429e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='false' so existing rows get a value; existing shops are treated
    # as not-yet-onboarded and will be redirected to /shop/onboard on next login.
    op.add_column(
        'shop',
        sa.Column('is_onboarded', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'is_onboarded')
    # ### end Alembic commands ###
