"""customer recovery code

Revision ID: e81d6ae1909a
Revises: 8a75f4f1420e
Create Date: 2026-04-29 12:34:11.804140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e81d6ae1909a'
down_revision: Union[str, Sequence[str], None] = '8a75f4f1420e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('recovery_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_customers_recovery_code'), 'customers', ['recovery_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_recovery_code'), table_name='customers')
    op.drop_column('customers', 'recovery_code')
    # ### end Alembic commands ###
